#! /usr/bin/env python3

import argparse
import sys
import os

def main(argv) -> int:
    targets = []
    names = []

    for basename in os.listdir("input/individual-plasma/seq"):
        name, ext = os.path.splitext(basename)
        target = f"output/individual-plasma/seq/{name}.csv"
        names.append(name)
        targets.append(target)

    print(f"output/individual-plasma/joined.csv: src/join-csv-files {' '.join(targets)}")
    print("	@ mkdir -p output/individual-plasma")
    print("	uv run python -- $^ $@")
    print()

    for name, target in zip(names, targets):
        print(f"{target}: src/make-individual-plasma-csv input/individual-plasma/seq/{name}.fasta")
        print("	@ mkdir -p output/individual-plasma/seq/")
        print("	uv run python -- $^ $@")
        print()

    return 0

if __name__ == "__main__":
    exit(main(sys.argv[1:]))
